### ISSUE TITLE
Lack of max-prefix option support

### ISSUE THREAD

**Issue by drustan** [jpcw/checkopenbgpd#3]
Hello,

I have spotted a missing feature. When the "max-prefix" option is set on a session, output is : 

 # /usr/local/bin/check_openbgpd
CHECKBGPCTL CRITICAL - Foo is U (outside range 0:)

even though current state is alright : 

 # bgpctl show
Neighbor                   AS    MsgRcvd    MsgSent  OutQ Up/Down  State/PrfRcvd
Foo                        42424     424242     424242          0 42w4d4h              4/42

It would be nice to add this ;-)

Thank you

**Comment by jpcw** [comment]
Thank you for your report.
Will fix it.
